-- MySQL Script generated by MySQL Workbench
-- Sat Jun  1 19:51:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_login
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_login` ;

-- -----------------------------------------------------
-- Schema test_login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_login` DEFAULT CHARACTER SET utf8 ;
USE `test_login` ;

-- -----------------------------------------------------
-- Table `test_login`.`tbl_rolle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_login`.`tbl_rolle` (
  `IDRolle` INT NOT NULL,
  `Bezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDRolle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_login`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_login`.`tbl_user` (
  `iduser` INT UNSIGNED NOT NULL,
  `nickname` VARCHAR(35) NOT NULL,
  `vorname` VARCHAR(35) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `eintritsdatum` DATETIME NOT NULL,
  `FIDrolle` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_tbl_user_tbl_rolle_idx` (`FIDrolle` ASC),
  CONSTRAINT `fk_tbl_user_tbl_rolle`
    FOREIGN KEY (`FIDrolle`)
    REFERENCES `test_login`.`tbl_rolle` (`IDRolle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
